feature: Fast-lane upgrade of CLI to latest version
eclipse-velocitas/devenv-devcontainer-setup pull request #31
Opened 2023-08-24 20:44 UTC by doosuu

Add code to postCreateCommand scripts which auto-upgrades the CLI to the latest available version.

2023-08-25 11:22 UTC, dennismeister93 commented
@doosuu refined it a bit

2023-08-28 08:16 UTC, doosuu commented on setup/src/common/scripts/postStartCommand.sh
> +wget -q --spider http://google.com
Not necessary to do an additional web request, better to simply exit early if line 38 does fail

2023-08-29 09:39 UTC, MP91 requested changes

2023-08-29 09:39 UTC, MP91 commented on test/requirements.txt
> +coveragepy-lcov==0.1.2
please check if we really need all the pytest-modules.
```suggestion
pytest==7.2.1
pytest-ordering==0.6
pytest-asyncio==0.20.3
pytest-cov==4.0.0
```

2023-08-29 09:39 UTC, MP91 commented on test/integration/test_poststart.py
> +    )
should we also check the version before updating? this would also test the download-method...

2023-08-29 09:39 UTC, MP91 commented on setup/src/common/scripts/postStartCommand.sh
> +if [ "$DESIRED_VERSION_TAG" != "$INSTALLED_VERSION" ]; then
could we do this check at first? so checking if needed != current would mean an early exit and no need to do any api-calls at all...

2023-08-29 10:45 UTC, MP91 approved these changes
lgtm

2023-08-29 11:04 UTC, merged