feature: Configurable devContainer base image
eclipse-velocitas/devenv-devcontainer-setup pull request #69
Opened 2024-05-30 09:33 UTC by doosuu

This PR introduces project variables which allow configuration of the devContainer base image upon sync.

2024-07-04 05:08 UTC, MP91 requested changes

2024-07-04 05:08 UTC, MP91 commented on manifest.json
> +            "basePath": "setup",
could we also add src here? or is the basepath not build for such usage?
```suggestion
            "basePath": "setup/src",
```

2024-07-04 05:08 UTC, MP91 commented on .github/workflows/ci.yml
> +          echo $PACKAGE_PATH
looks like debugging? please remove if not needed

2024-07-04 05:08 UTC, MP91 commented on setup/src/python/common/Dockerfile
> +FROM ${{ devContainerBaseImageUriPrefix }}/python:${{ devContainerBaseImageTag }}
we also have the language as variable, should we add this here? or directly in the manifest somehow?

In general I don't like that a user will need to know that cpp or python is still added to the URI. maybe someone just has one image for python but the name does not end with python...

2024-07-04 05:08 UTC, MP91 commented on manifest.json
please check all pathes regarding basePath as mentioned

2024-07-08 11:27 UTC, doosuu commented on manifest.json
src should not be included in the base path since some of these components include assets in <basePath>/ and should not be fored to go upward one directory to access those resources. i.e units.yaml

2024-07-08 11:58 UTC, MP91 approved these changes
lgtm

2024-07-08 12:03 UTC, merged